on: 
  push:
    branches-ignore: 
      - 'main'

jobs:
  # 1) Generate Matrix
  setup:
    name: Setup Matrix
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.set.outputs.config }}
    steps:
        - uses: actions/checkout@v3

        - run: cat config.json

        - id: set
          run: |
            echo "config=$(cat config.json | jq -c)" >> $GITHUB_OUTPUT


  # 2) Matrix Build
  build_matrix:
    needs: [setup]
    strategy:
      fail-fast: false
      matrix: 
        include: ${{ fromJson(needs.setup.outputs.config) }}
    runs-on: ${{ matrix.runner }}
    steps:
      # Checkout Build Scripts
      - uses: actions/checkout@v3
        with:
          ref: main

      # Checkout Source
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          path: KOS

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Goto commit prior to our Actions additions
      - run: cd KOS && git reset HEAD^

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build Container
      # - name: Build Container
      #   run: |
      #     export SHA=$(git rev-parse HEAD)
      #     export ARCH=$(echo "${{ matrix.arch }}" | cut -d "/" -f2)
      #     docker buildx build \
      #       --push \
      #       --cache-from=type=gha,mode=max \
      #       --cache-to=type=gha,mode=max \
      #       --platform=${{ matrix.arch }} \
      #       --build-arg CONFIG_FILE=${{ matrix.config }} \
      #       --build-arg BUILD_TYPE=kos \
      #       --target gdb-build \
      #       -t ghcr.io/cepawiel/temp-toolchain-${{ matrix.type }}:$SHA-${{ matrix.tag }}-$ARCH \
      #       .

      - id: set
        run: |
          echo "sha=$(cd KOS && git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "arch=$(echo "${{ matrix.arch }}" | cut -d "/" -f2)" >> $GITHUB_OUTPUT

      - name: Build base Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ matrix.arch }}
          build-args: |
            CONFIG_FILE=${{ matrix.config }}
            BUILD_TYPE=kos
          tags: |
            ghcr.io/cepawiel/temp-toolchain-${{ matrix.type }}:${{ steps.set.outputs.sha }}-${{ matrix.tag }}-${{ steps.set.outputs.arch }}
          cache-from: type=gha,scope=cached-stage
          cache-to: type=gha,scope=cached-stage,mode=max
          target: gdb-build
          push: true

  multi_arch_containers:
    needs: [build_matrix]
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
