on: 
  push:
    branches-ignore: 
      - 'main'

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - run: git checkout HEAD^
    - run: git log
      # - run: ./sync_branches.sh
