on: 
  push:
    branches-ignore: 
      - 'main'

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Checkout Build Scripts
    - uses: actions/checkout@v3
      with:
        ref: main

    # Checkout Source
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
        path: KOS

    - run: cd KOS && git reset HEAD^

    - name: Build Container
      run: |
        docker buildx build \
          --platform=linux/amd64 \
          --build-arg CONFIG_FILE=config.mk.testing.sample \
          --build-arg BUILD_TYPE=kos \
          --target gdb-build \
          .
        
        
