on: 
  push:
    branches-ignore: 
      - 'main'

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - run: git reset HEAD^

    - name: Build Container
      run: |
        ls -la
        docker buildx build \
          --platform=linux/arm64 \
          --build-arg CONFIG_FILE=config.mk.testing.sample \
          --build-arg BUILD_TYPE=kos \
          --target build-gdb \
          .
        
