on: 
  push:
    branches: 
      - 'main'

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: builder
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Move Files
        run: |
          cp builder/sync_branches.sh sync_branches.sh
          cp builder/build_workflow.yml build_workflow.yml
    
      - name: Add Upstream Remote
        run: |
          cd builder 
          git remote add upstream https://github.com/KallistiOS/KallistiOS
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions"
          git fetch -u upstream

      - name: Sync Branches
        run: ./sync_branches.sh
        
