on: 
  push:
    branches: 
      - 'main'

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
            path: builder
    
      - name: Add Upstream Remote
        run: cd builder && git remote add upstream git@github.com:KallistiOS/KallistiOS.git

      - name: Sync Branches
        run: ./sync_branches.sh
